# Generated by Django 3.1 on 2020-08-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200823_1639'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
